#!/usr/bin/env bash
#
# Regenerates docs/METRICS.md. Every number in the CV must come out of a command
# rather than a memory, so this script is the source and METRICS.md is its
# output:
#
#     bash scripts/metrics.sh > docs/METRICS.md
#
# Set SKIP_TESTS=1 to print the cheap numbers without the ~2 minute unit run.
#
# Runs under Git Bash on Windows and bash on Linux/CI. Requires node + npx only
# — no cloc, no tokei: LOC comes from `git ls-files`, so it counts exactly what
# is committed and never wanders into node_modules or dist.
set -euo pipefail

cd "$(dirname "$0")/.."

COMMIT="$(git rev-parse --short HEAD)"
COMMIT_DATE="$(git log -1 --format=%cd --date=format:%Y-%m-%d)"
MEASURED_AT="$(date +%Y-%m-%d)"
DIRTY=""
if [ -n "$(git status --porcelain)" ]; then
  DIRTY=" (working tree dirty at measurement time)"
fi

# --- Source size -------------------------------------------------------------
# Tracked files only. Tests are counted separately rather than folded in: a
# combined figure flatters the app size and hides the test ratio, which is the
# more interesting number.
loc_of() {
  # shellcheck disable=SC2312
  git ls-files -z "$@" | xargs -0 cat 2>/dev/null | wc -l | tr -d ' '
}

APP_LOC="$(git ls-files -z 'src/*.ts' 'src/*.tsx' 'src/**/*.ts' 'src/**/*.tsx' \
  | tr '\0' '\n' | grep -v '\.test\.' | tr '\n' '\0' \
  | xargs -0 cat 2>/dev/null | wc -l | tr -d ' ')"
TEST_LOC="$(git ls-files -z 'src/**/*.test.ts' 'src/**/*.test.tsx' \
  | xargs -0 cat 2>/dev/null | wc -l | tr -d ' ')"
E2E_LOC="$(loc_of 'e2e/*.ts')"

APP_FILES="$(git ls-files 'src/*.ts' 'src/*.tsx' 'src/**/*.ts' 'src/**/*.tsx' | grep -cv '\.test\.')"
TEST_FILES="$(git ls-files 'src/**/*.test.ts' 'src/**/*.test.tsx' | wc -l | tr -d ' ')"
E2E_SPECS="$(git ls-files 'e2e/*.spec.ts' | wc -l | tr -d ' ')"

# --- Screens -----------------------------------------------------------------
# Counted off the router, not off a folder listing: a page component with no
# route is not a screen a user can reach.
ROUTE_PATHS="$(grep -c "path: '" src/router.tsx)"
INDEX_ROUTES="$(grep -c 'index: true' src/router.tsx)"
SCREENS=$(( ROUTE_PATHS + INDEX_ROUTES ))

LAZY_PAGES="$(grep -c 'lazy(() => import' src/router.tsx)"

# --- Unit tests --------------------------------------------------------------
PASSED="n/a (SKIP_TESTS=1)"
SUITES="n/a"
if [ "${SKIP_TESTS:-0}" != "1" ]; then
  OUT=".metrics-vitest.json"
  # `|| true`: a red suite must still produce a report. The number printed is
  # `passed`, and the failure count below it is what makes a red run obvious.
  npx vitest run --reporter=json --outputFile="$OUT" >/dev/null 2>&1 || true
  PASSED="$(node -p "require('./$OUT').numPassedTests")"
  FAILED="$(node -p "require('./$OUT').numFailedTests")"
  SUITES="$(node -p "require('./$OUT').numTotalTestSuites")"
  rm -f "$OUT"
  if [ "$FAILED" != "0" ]; then
    PASSED="$PASSED passed, **$FAILED FAILED**"
  fi
fi

cat <<EOF
# Metrics — TryBuy storefront

Generated by \`bash scripts/metrics.sh\`. Do not hand-edit: re-run the script.

- **Measured:** $MEASURED_AT
- **Commit:** \`$COMMIT\` ($COMMIT_DATE)$DIRTY

| Metric | Value | How it is counted |
|---|---|---|
| Unit tests passing | $PASSED | \`vitest run --reporter=json\` → \`numPassedTests\` |
| Unit test files | $TEST_FILES | tracked \`src/**/*.test.ts(x)\` |
| Test suites | $SUITES | \`numTotalTestSuites\` |
| E2E specs | $E2E_SPECS | tracked \`e2e/*.spec.ts\` (Playwright; needs a live gateway, not run in CI) |
| Screens (routes) | $SCREENS | \`path:\` + \`index: true\` entries in \`src/router.tsx\` |
| Lazy-loaded pages | $LAZY_PAGES | \`lazy(() => import\` in \`src/router.tsx\` |
| App source LOC | $APP_LOC | tracked \`src/**/*.ts(x)\` excluding \`*.test.*\` |
| Unit test LOC | $TEST_LOC | tracked \`src/**/*.test.ts(x)\` |
| E2E LOC | $E2E_LOC | tracked \`e2e/*.ts\` |
| App source files | $APP_FILES | tracked \`src/**/*.ts(x)\` excluding \`*.test.*\` |

## Not measured here

- **Backend throughput** (req/s, cached vs uncached). Belongs on the machine
  that serves the traffic — running k6 or autocannon from a laptop over the
  public internet measures the link, not the server. Run it on the EC2 host and
  record the instance type, VU count and duration alongside the result.
- **REST route count.** Counted from the backend's Swagger JSON, which is a
  backend repo concern.
- **Playwright pass count.** The specs need a live gateway inside the backend's
  scheduled window plus a browser download, so CI does not run them and this
  script does not either. Run \`npm run test:e2e\` during the window.
EOF
